### ISSUE TITLE
getting 404 when trying to generate address

### ISSUE THREAD

**Issue by ad2003** [IndieSquare/btcpayunity#11]
Hi! 

I am getting a 404 error message when trying to generate an invoice on my project https://quitebeyond.com/musicbox/. 

Any idea why this happens? Maybe it has something to do with btcpayserver update?

Thank you!

**Comment by mandelmonkey** [comment]
hi I think it is due to the update around facades, the brilliant @hypergori is looking into it

**Comment by hypergori** [comment]
My dev environment is totally screwed up.  It may take a while to fix my Visual Studio.

**Comment by hypergori** [comment]
Fixed. You need to do paring with a new code. 
https://github.com/IndieSquare/btcpayunity/releases/tag/1.1.3

BTCPay removed the POS facade. So, I changed the code to use Marchant facade which is the only one used in BTCPay,
