### ISSUE TITLE
Error Message in Unity

### ISSUE THREAD

**Issue by ad2003** [IndieSquare/btcpayunity#2]
Hello!
Getting the following error Log when opening Unity 2018.2 and importing the current release into an new project:

`Assets/Scripts/BTCPayUnity.cs(27,16): error CS1644: Feature `asynchronous functions' cannot be used because it is not part of the C# 4.0 language specification`

When following the tut (https://blog.indiesquare.me/develop-a-lightning-game-with-unity-btcpay-sdk-part-2-set-up-unity-project-d4fa68cec3bf - thank you for this!)  and importing "Download In-Game Shop version of Survival Shooter" everything worked fine.

Thanks.

**Comment by ad2003** [comment]
https://github.com/Microsoft/MixedRealityToolkit-Unity/issues/739#issuecomment-310802787

**Comment by masashinaka** [comment]
Hi  @ad2003 . Thanks for comments.  How did you fix it ?  I am guessing you have done either,
1. .net version change on Unity setting to 4.x from 3.x 
2.  import asset for async-await from Unity asset store
Because I want to make the documentation better, I want to know that.
Your feedback helps other game devs.

**Comment by ad2003** [comment]
Hi! Correct: 1. Under Project Settings I changed "Scripting Runtime Version" from 3.5 to 4. 
This worked. I could open the project and fiddle around a bit. I could connect to my server and lightning pay works. I wanted to make a test build but now I am getting errors:

`ArgumentException: The Assembly log4net is referenced by BitCoinSharp ('Assets/Dlls/BitCoinSharp.dll'). But the dll is not allowed to be included or could not be found.
UnityEditor.AssemblyHelper.AddReferencedAssembliesRecurse (System.String assemblyPath, System.Collections.Generic.List`1[T] alreadyFoundAssemblies, System.String[] allAssemblyPaths, System.String[] foldersToSearch, System.Collections.Generic.Dictionary`2[TKey,TValue] cache, UnityEditor.BuildTarget target) (at C:/buildslave/unity/build/Editor/Mono/AssemblyHelper.cs:155)
UnityEditor.AssemblyHelper.AddReferencedAssembliesRecurse (System.String assemblyPath, System.Collections.Generic.List`1[T] alreadyFoundAssemblies, System.String[] allAssemblyPaths, System.String[] foldersToSearch, System.Collections.Generic.Dictionary`2[TKey,TValue] cache, UnityEditor.BuildTarget target) (at C:/buildslave/unity/build/Editor/Mono/AssemblyHelper.cs:161)
UnityEditor.AssemblyHelper.AddReferencedAssembliesRecurse (System.String assemblyPath, System.Collections.Generic.List`1[T] alreadyFoundAssemblies, System.String[] allAssemblyPaths, System.String[] foldersToSearch, System.Collections.Generic.Dictionary`2[TKey,TValue] cache, UnityEditor.BuildTarget target) (at C:/buildslave/unity/build/Editor/Mono/AssemblyHelper.cs:161)
UnityEditor.AssemblyHelper.FindAssembliesReferencedBy (System.String[] paths, System.String[] foldersToSearch, UnityEditor.BuildTarget target) (at C:/buildslave/unity/build/Editor/Mono/AssemblyHelper.cs:195)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)
`

`Build completed with a result of 'Failed'
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)`

`UnityEditor.BuildPlayerWindow+BuildMethodException: 3 errors
  at UnityEditor.BuildPlayerWindow+DefaultBuildMethods.BuildPlayer (UnityEditor.BuildPlayerOptions options) [0x0021f] in C:\buildslave\unity\build\Editor\Mono\BuildPlayerWindowBuildMethods.cs:187 
  at UnityEditor.BuildPlayerWindow.CallBuildMethods (System.Boolean askForBuildLocation, UnityEditor.BuildOptions defaultBuildOptions) [0x0007f] in C:\buildslave\unity\build\Editor\Mono\BuildPlayerWindowBuildMethods.cs:94 
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)`


edited: added the correct error log.

**Comment by hypergori** [comment]
Please try to download the log4net dll here and put it in <Project>/Assets/Dlls/ folder.

https://logging.apache.org/log4net/download_log4net.cgi

We will make the dependency management more elegant. #3

**Comment by ad2003** [comment]
Nice! Thank you! I used log4net-2.0.8-bin-oldkey.zip\log4net-2.0.8\bin\net\4.0\release and put it in the DLLs folder. Under Player Settings I checked API Compatibility Level to NET 4.X. and now it works!
